@startuml ClassDiagram
hide circle
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam linetype ortho
skinparam classFontStyle bold
skinparam classFontSize 14
skinparam nodesep 50
skinparam ranksep 50
skinparam class {
  BackgroundColor White
  HeaderBackgroundColor #E8E8E8
  BorderColor #999999
}


class "AuthController" as AuthCtrl {
  - service : AuthService
  --
  + forgotPassword(forgotPasswordDto : AuthForgotPasswordDto) : Promise<{ message: string }>
}

class "AuthService" as AuthSvc {
  - accountsService : AccountsService
  --
  + forgotPassword(email : string) : Promise<{ message: string }>
}

class "AccountsService" as AccSvc {
  + findByEmail(email : string) : Promise<Account | null>
}

class "MailService" as MailSvc {
  + forgotPassword(mailData : MailDataInterface) : Promise<void>
}

class "AuthForgotPasswordDto" as ForgotPwdDto {
  - email : string
}

class "AccountEntity" as AccountEntity {
  - accountId : string
  - email : string | null
}

' ---- Relationships ----
AuthCtrl --> AuthSvc : <<association>>
AuthSvc --> AccSvc : <<association>>
AuthSvc --> MailSvc : <<association>>

AuthCtrl ..> ForgotPwdDto : <<dependency>>
AccSvc ..> AccountEntity : <<dependency>>

@enduml
