@startuml ClassDiagram
hide circle
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam linetype ortho
skinparam classFontStyle bold
skinparam classFontSize 14
skinparam nodesep 50
skinparam ranksep 50
skinparam class {
  BackgroundColor White
  HeaderBackgroundColor #E8E8E8
  BorderColor #999999
}


class "AuthController" as AuthCtrl {
  - service : AuthService
  ...
  --
  + update(request, accountDto : AuthUpdateDto) : Promise<Account | null>
  ...
}

class "AuthService" as AuthSvc {
  - accountsService : AccountsService
  - refreshTokensService : RefreshTokensService
  ...
  --
  + update(accountId : string, userDto : AuthUpdateDto) : Promise<Account | null>
  ...
}

class "AccountsService" as AccSvc {
  ...
  --
  + findById(id : string) : Promise<Account | null>
  + update(id : string, updateAccountDto : UpdateAccountDto) : Promise<Account | null>
  ...
}

class "RefreshTokensService" as RefTokenSvc {
  ...
  --
  + revokeByAccountId(accountId : string) : Promise<void>
  ...
}

class "AuthUpdateDto" as UpdateDto {
  - password? : string
  - oldPassword? : string
  ...
  --
}

class "AccountEntity" as AccountEntity {
  - accountId : string
  - passwordHash : string | null
  ...
  --
}

' ---- Relationships ----
AuthCtrl --> AuthSvc : <<association>>
AuthSvc --> AccSvc : <<association>>
AuthSvc --> RefTokenSvc : <<association>>

AuthCtrl ..> UpdateDto : <<dependency>>
AccSvc ..> AccountEntity : <<dependency>>

@enduml
