@startuml ClassDiagram
hide circle
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam linetype ortho
skinparam classFontStyle bold
skinparam classFontSize 14
skinparam nodesep 50
skinparam ranksep 50
skinparam class {
  BackgroundColor White
  HeaderBackgroundColor #E8E8E8
  BorderColor #999999
}


class "UserProfilesController" as UserProfCtrl {
  - userProfilesService : UserProfilesService
  ...
  --
  + findAll(query : QueryUserProfileDto) : Promise<{ data, meta }>
  ...
}

class "UserProfilesService" as UserProfSvc {
  ...
  --
  + findAll(query : QueryUserProfileDto) : Promise<{ data: UserProfileEntity[]; total: number }>
  ...
}

class "QueryUserProfileDto" as QueryDto {
  - page? : number
  - limit? : number
  - email? : string
  - phone? : string
  - full_name? : string
  - gender? : string
  ...
  --
}

class "UserProfileEntity" as UserProfileEntity {
  - user_id : string
  - full_name : string
  - email : string | null
  - phone : string | null
  - date_of_birth : Date | null
  - gender : string | null
  - avatar_url : string | null
  - is_banned : boolean
  ...
  --
}

' ---- Relationships ----
UserProfCtrl --> UserProfSvc : <<association>>

UserProfCtrl ..> QueryDto : <<dependency>>
UserProfSvc ..> UserProfileEntity : <<dependency>>

@enduml
