@startuml ClassDiagram
hide circle
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam linetype ortho
skinparam classFontStyle bold
skinparam classFontSize 14
skinparam nodesep 50
skinparam ranksep 50
skinparam class {
  BackgroundColor White
  HeaderBackgroundColor #E8E8E8
  BorderColor #999999
}


class "DoctorSchedulesController" as SchCtrl {
  - doctorSchedulesService : DoctorSchedulesService
  ...
  --
  + create(dto : CreateDoctorScheduleDto) : Promise<DoctorScheduleEntity>
  ...
}

class "DoctorSchedulesService" as SchSvc {
  - scheduleRepository : Repository<DoctorScheduleEntity>
  ...
  --
  + create(dto : CreateDoctorScheduleDto) : Promise<DoctorScheduleEntity>
  ...
}

class "CreateDoctorScheduleDto" as CreateDto {
  - doctor_id : string
  - clinic_id : string
  - shift_id? : string | null
  - work_date : string
  - room_id? : string | null
  - max_patients? : number
  - notes? : string | null
  - status? : ScheduleStatus
  ...
  --
}

class "DoctorScheduleEntity" as SchEntity {
  - schedule_id : string
  - doctor_id : string
  - clinic_id : string
  - shift_id : string | null
  - work_date : Date
  - room_id : string | null
  - max_patients : number
  - status : string
  - notes : string | null
  ...
  --
}

' ---- Relationships ----
SchCtrl --> SchSvc : <<association>>

SchCtrl ..> CreateDto : <<dependency>>
SchSvc ..> SchEntity : <<dependency>>

@enduml
