@startuml ClassDiagram
hide circle
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam linetype ortho
skinparam classFontStyle bold
skinparam classFontSize 14
skinparam nodesep 50
skinparam ranksep 50
skinparam class {
  BackgroundColor White
  HeaderBackgroundColor #E8E8E8
  BorderColor #999999
}


class "PatientsController" as PatCtrl {
  - patientsService : PatientsService
  ...
  --
  + update(patient_id : string, updatePatientDto : UpdatePatientDto) : Promise<PatientEntity>
  ...
}

class "PatientsService" as PatSvc {
  - patientsRepository : Repository<PatientEntity>
  ...
  --
  + update(patient_id : string, updatePatientDto : UpdatePatientDto) : Promise<PatientEntity>
  ...
}

class "UpdatePatientDto" as UpdateDto {
  - full_name? : string
  - date_of_birth? : string
  - gender? : string
  - phone? : string
  - email? : string
  - address? : string
  - blood_type? : string
  - allergies? : string[]
  - insurance_number? : string
  ...
  --
}

class "PatientEntity" as PatEntity {
  - patient_id : string
  - patient_code : string
  - full_name : string
  - phone : string | null
  - email : string | null
  ...
  --
}

' ---- Relationships ----
PatCtrl --> PatSvc : <<association>>

PatCtrl ..> UpdateDto : <<dependency>>
PatSvc ..> PatEntity : <<dependency>>

@enduml
