@startuml ClassDiagram
hide circle
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam linetype ortho
skinparam classFontStyle bold
skinparam classFontSize 14
skinparam nodesep 50
skinparam ranksep 50
skinparam class {
  BackgroundColor White
  HeaderBackgroundColor #E8E8E8
  BorderColor #999999
}


class "MedicalRecordsController" as RecCtrl {
  - service : MedicalRecordsService
  ...
  --
  + remove(record_id : string) : Promise<MedicalRecordEntity>
  ...
}

class "MedicalRecordsService" as RecSvc {
  - recordsRepository : Repository<MedicalRecordEntity>
  ...
  --
  + remove(record_id : string) : Promise<MedicalRecordEntity>
  ...
}

class "MedicalRecordEntity" as RecEntity {
  - record_id : string
  - patient_id : string
  - record_status : string
  ...
  --
}

' ---- Relationships ----
RecCtrl --> RecSvc : <<association>>

RecSvc ..> RecEntity : <<dependency>>

@enduml
