@startuml ClassDiagram
hide circle
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam linetype ortho
skinparam classFontStyle bold
skinparam classFontSize 14
skinparam nodesep 50
skinparam ranksep 50
skinparam class {
  BackgroundColor White
  HeaderBackgroundColor #E8E8E8
  BorderColor #999999
}


class "AppointmentsController" as ApptCtrl {
  - appointmentsService : AppointmentsService
  --
  + changeStatus(id : string, dto : ChangeAppointmentStatusDto) : Promise<AppointmentEntity>
}

class "AppointmentsService" as ApptSvc {
  - appointmentRepository : Repository<AppointmentEntity>
  --
  + changeStatus(id : string, dto : ChangeAppointmentStatusDto) : Promise<AppointmentEntity>
}

class "ChangeAppointmentStatusDto" as StatusDto {
  - status : AppointmentStatus
  - changed_by : string
  - reason? : string
}

class "AppointmentEntity" as ApptEntity {
  - appointment_id : string
  - payment_id : string | null
  - payment_status : string
  - status : string
}

class "ServiceEntity" as SvcEntity {
  - service_id : string
  - service_name : string
  - base_price : number | null
  - currency : string
}

' ---- Relationships ----
ApptCtrl --> ApptSvc : <<association>>

ApptCtrl ..> StatusDto : <<dependency>>
ApptSvc ..> ApptEntity : <<dependency>>

ApptEntity --> SvcEntity : <<association>>

@enduml
