@startuml ClassDiagram
hide circle
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam linetype ortho
skinparam classFontStyle bold
skinparam classFontSize 14
skinparam nodesep 50
skinparam ranksep 50
skinparam class {
  BackgroundColor White
  HeaderBackgroundColor #E8E8E8
  BorderColor #999999
}


class "AppointmentsController" as ApptCtrl {
  - appointmentsService : AppointmentsService
  --
  + findByPatient(patientId : string, status? : string) : Promise<AppointmentEntity[]>
  + findByDoctor(doctorId : string, date? : string) : Promise<AppointmentEntity[]>
  + create(dto : CreateAppointmentDto) : Promise<AppointmentEntity>
}

class "AppointmentsService" as ApptSvc {
  - appointmentRepository : Repository<AppointmentEntity>
  - doctorScheduleRepository : Repository<DoctorScheduleEntity>
  --
  + findByPatient(patientId : string, status? : string) : Promise<AppointmentEntity[]>
  + findByDoctor(doctorId : string, date? : string) : Promise<AppointmentEntity[]>
  + create(dto : CreateAppointmentDto) : Promise<AppointmentEntity>
}

class "AppointmentEntity" as ApptEntity {
  - appointment_id : string
  - appointment_code : string
  - patient_id : string
  - doctor_id : string
  - appointment_date : Date
  - appointment_time : string
  - status : string
}

class "SpecialtyEntity" as SpecEntity {
  - specialty_id : string
  - specialty_name : string
}

class "DoctorScheduleEntity" as SchedEntity {
  - schedule_id : string
  - doctor_id : string
  - work_date : Date
}

' ---- Relationships ----
ApptCtrl --> ApptSvc : <<association>>

ApptSvc ..> ApptEntity : <<dependency>>
ApptSvc ..> SpecEntity : <<dependency>>
ApptSvc ..> SchedEntity : <<dependency>>

@enduml
