@startuml ClassDiagram
hide circle
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam linetype ortho
skinparam classFontStyle bold
skinparam classFontSize 14
skinparam nodesep 50
skinparam ranksep 50
skinparam class {
  BackgroundColor White
  HeaderBackgroundColor #E8E8E8
  BorderColor #999999
}


class "TreatmentPlansController" as PlanCtrl {
  - treatmentPlansService : TreatmentPlansService
  ...
  --
  + update(plan_id : string, updateTreatmentPlanDto : UpdateTreatmentPlanDto) : Promise<TreatmentPlanEntity>
  ...
}

class "TreatmentPlansService" as PlanSvc {
  - treatmentPlansRepository : Repository<TreatmentPlanEntity>
  ...
  --
  + update(plan_id : string, updateTreatmentPlanDto : UpdateTreatmentPlanDto) : Promise<TreatmentPlanEntity>
  ...
}

class "UpdateTreatmentPlanDto" as UpdateDto {
  - plan_name? : string
  - objectives? : string
  - duration_weeks? : number
  - status? : string
  ...
  --
}

class "TreatmentPlanEntity" as PlanEntity {
  - plan_id : string
  - plan_name : string | null
  - status : string
  ...
  --
}

' ---- Relationships ----
PlanCtrl --> PlanSvc : <<association>>

PlanCtrl ..> UpdateDto : <<dependency>>
PlanSvc ..> PlanEntity : <<dependency>>

@enduml
