@startuml SequenceDiagram
skinparam shadowing false
skinparam sequenceMessageAlign center
actor "User" as user
boundary "ProfilePage" as form
participant ":UserProfilesController" as ctrl
participant ":UserProfilesService" as profSvc
entity "UserProfileEntity" as profEntity
database "PostgreSQL" as db

user -> form : 1. Open My Profile page
activate user
activate form

form -> ctrl : 2. GET /api/v1/user-profiles/{id}
activate ctrl

ctrl -> profSvc : 3. findOne(id)
activate profSvc

profSvc -> profEntity : 4. findOne(userId)
activate profEntity
profEntity -> db : 5. SELECT user_profile WHERE user_id
activate db
db --> profEntity : 6. return result
deactivate db
profEntity --> profSvc : 7. return UserProfile
deactivate profEntity

profSvc --> ctrl : 8. return UserProfileEntity
deactivate profSvc

ctrl --> form : 9. 200 OK { UserProfileEntity }
deactivate ctrl

form --> user : 10. Display profile\n(name, email, phone, avatar)
deactivate form

deactivate user

@enduml
