@startuml SequenceDiagram
skinparam shadowing false
skinparam sequenceMessageAlign center
actor "Staff" as user
boundary "PatientListView" as form
participant ":PatientsController" as ctrl
participant ":PatientsService" as patSvc
entity "PatientEntity" as patEntity
database "PostgreSQL" as db

user -> form : 1. Open patient management page
activate user
activate form

form -> ctrl : 2. GET /api/v1/patients
activate ctrl

ctrl -> patSvc : 3. findAll()
activate patSvc

patSvc -> patEntity : 4. find()
activate patEntity
patEntity -> db : 5. SELECT patients
activate db
db --> patEntity : 6. return result
deactivate db
patEntity --> patSvc : 7. return PatientEntity[]
deactivate patEntity

patSvc --> ctrl : 8. return PatientEntity[]
deactivate patSvc

ctrl --> form : 9. 200 OK PatientEntity[]
deactivate ctrl

form --> user : 10. Display patient list
deactivate form

deactivate user

@enduml
